title: AppSec Israel 2025
description: OWASP AppSec Israel annual conference - 2025 edition!

year: 2025

# Conference dates
dates:  June 5, 2025
#trainingday: Tuesday, October 27th
#confday: Wednesday, October 28th

logoUrl: /2025/AppSecIL_logo.png
# sched: owaspappsecil2023.sched.com
